# Generated by Django 2.2.3 on 2020-09-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0001_initial'),
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea1_not', models.FloatField(blank=True, null=True, verbose_name='Nota de Tarea 1')),
                ('tarea2_not', models.FloatField(blank=True, null=True, verbose_name='Nota de Tarea 2')),
                ('tarea3_not', models.FloatField(blank=True, null=True, verbose_name='Nota de Tarea 3')),
                ('tarea4_not', models.FloatField(blank=True, null=True, verbose_name='Nota de Tarea 4')),
                ('tarea5_not', models.FloatField(blank=True, null=True, verbose_name='Nota de Tarea 5')),
                ('tarea6_not', models.FloatField(blank=True, null=True, verbose_name='Nota de Tarea 6')),
                ('tarea7_not', models.FloatField(blank=True, null=True, verbose_name='Nota de Tarea 7')),
                ('tarea8_not', models.FloatField(blank=True, null=True, verbose_name='Nota de Tarea 8')),
                ('evaluacion1_not', models.FloatField(blank=True, null=True, verbose_name='Nota de Evaluación 1')),
                ('evaluacion2_not', models.FloatField(blank=True, null=True, verbose_name='Nota de Evaluación 2')),
                ('final_nota', models.FloatField(blank=True, null=True, verbose_name='Nota de Final obtenida')),
                ('observaciones_not', models.CharField(blank=True, max_length=30, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno', verbose_name='Alumno con cédula')),
                ('nota_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Materia', verbose_name='Materia')),
            ],
        ),
    ]
