# Generated by Django 2.2.3 on 2020-09-02 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_doce', models.CharField(max_length=10, verbose_name='N° de Cédula')),
                ('especialidad_doce', models.CharField(max_length=150, verbose_name='Especialidad')),
                ('fotografia_doce', models.ImageField(blank=True, null=True, upload_to='docente/', verbose_name='Fotografía')),
                ('docente_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Materia', verbose_name='Materia a impartir')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
