# Generated by Django 2.2.3 on 2020-09-02 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_alu', models.CharField(max_length=10, verbose_name='N° de Cedula')),
                ('sexo', models.CharField(blank=True, choices=[('masculio', 'Masculino'), ('femenino', 'Femenino')], max_length=100, null=True)),
                ('direccion_alu', models.CharField(max_length=100, verbose_name='Dirección')),
                ('email_personal_alu', models.EmailField(max_length=254, verbose_name='Email Personal')),
                ('fotografia_alu', models.ImageField(blank=True, null=True, upload_to='alumno/', verbose_name='Fotografía')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('estudiante', 'Permiso de estudiante'), ('profesor', 'Permiso de profesor')),
            },
        ),
        migrations.CreateModel(
            name='Anio_Lectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inico_anio', models.DateField(verbose_name='Fecha de Inicio del Año Lectivo')),
                ('fecha_final_anio', models.DateField(verbose_name='Fecha de Fin del Año Lectivo')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grado', models.CharField(max_length=20, verbose_name='Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paralelo', models.CharField(max_length=10, verbose_name='Paralelo')),
                ('paralelo_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Grado', verbose_name='Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField(verbose_name='Fecha de Matrícula')),
                ('matricula_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno', verbose_name='Alumno con cédula')),
                ('matricula_anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Anio_Lectivo', verbose_name='Año Lectivo')),
                ('matricula_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Grado', verbose_name='Grado')),
                ('matricula_paraleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Paralelo', verbose_name='Paralelo')),
            ],
        ),
    ]
