# Generated by Django 2.2.3 on 2020-09-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='titulo de la evaluacion')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mat', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion_mat', models.CharField(max_length=50, verbose_name='Descripción')),
                ('alumno_id', models.ManyToManyField(to='alumno.Alumno', verbose_name='Alumno con cédula')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo de la tarea')),
                ('descripcion_2', models.TextField(verbose_name='Descripcion')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tarea_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TrabajoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo', models.FileField(blank=True, null=True, upload_to='trabajos/')),
                ('completada', models.BooleanField(default=False)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno', verbose_name='Alumno con cedula')),
                ('tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Tarea', verbose_name='Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoEva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo', models.FileField(blank=True, null=True, upload_to='evaluaiones/')),
                ('completada', models.BooleanField(default=False)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno', verbose_name='Alumno con cedula')),
                ('evaluacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Evaluacion', verbose_name='Evaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='evaluacion_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Materia', verbose_name='Materia'),
        ),
    ]
